// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBopsyCaDt5a-H64mwCbPWwtd_kJBji818',
    appId: '1:1029871453350:web:f905eec96fd9db5a5fe067',
    messagingSenderId: '1029871453350',
    projectId: 'cipherschoolsassignment-5c72c',
    authDomain: 'cipherschoolsassignment-5c72c.firebaseapp.com',
    storageBucket: 'cipherschoolsassignment-5c72c.appspot.com',
    measurementId: 'G-284BZEQSM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBii1nQxLOV8Tc3-jqeFydtWMQFbdZzpRk',
    appId: '1:1029871453350:android:f871df52967711b45fe067',
    messagingSenderId: '1029871453350',
    projectId: 'cipherschoolsassignment-5c72c',
    storageBucket: 'cipherschoolsassignment-5c72c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxyZR1F-5KwQrvwniH99Pjb_DELN2MAc',
    appId: '1:1029871453350:ios:8ed18736980fbe0e5fe067',
    messagingSenderId: '1029871453350',
    projectId: 'cipherschoolsassignment-5c72c',
    storageBucket: 'cipherschoolsassignment-5c72c.appspot.com',
    iosBundleId: 'com.example.cipherschoolsAssignment',
  );
}
